
TEXTS = {
    'uz': {
        'start_welcome': "Assalomu aleykum Universal Media Bot ga\nxush kelibsiz\n@universal_media_uz_bot orqali quyidagilarni yuklab\nolishingiz mumkin\n\n●Instagram - post, stories, reels, rasm;\n●YouTube - video, shorts, audio;\n●Tik Tok - suv belgisiz video, rasm;\n●Facebook - reels;\n●VK - video, rasm;\n●Pinterest - rasm, video;\n●Snapchat - rasm, video;\n●Likee - rasm, video;\n●Threads - rasm, video;\n●Bigo Live - video, efir;\nMedia yuklashni boshlash uchun\nuning havolasini yuboring.",
        'search_searching': "🔥 '{query}' bo'yicha top musiqalar qidirilmoqda...",
        'search_top_loading': "🔥 Top o'zbek musiqalari qidirilmoqda...",
        'search_not_found': "Hozircha top musiqalar topilmadi.",
        'getting_info': "⏳ Ma'lumot olinmoqda...",
        'search_music_searching': "🔎 Muzika qidirilmoqda: {query}...",
        'nothing_found': "Hech narsa topilmadi 😔",
        'no_favorites': "❤️ Sizda hozircha saqlangan musiqalar yo'q.",
        'favorites_header': "❤️ <b>Sevimli Musiqalar:</b>\n\n",
        'saved': "❤️ Saqlandi!",
        'already_saved': "Allaqachon mavjud!",
        'saved_msg': "✅ Saqlandi: {title}",
        'error_no_link': "Saqlash uchun havola topilmadi.",
        'error_general': "Xatolik: {error}",
        'choose_quality': "❤️ Tanlandi: {title}\n\nSifatni tanlang:",
        'lang_choose': "💬 O'zgartirmoqchi bo'lgan tilni tanlang va siz tanlagan tilda bot ishlashni boshlaydi.\n\n(Interfeys tilini tanlash uchun, pastdagi tugmalardan birini bosishingiz mumkin)",
        'lang_selected': "✅ Til o'zgartirildi: O'zbekcha 🇺🇿",
        'downloading': "Yuklanmoqda... 0%",
        'downloading_percent': "Yuklanmoqda... {percent} ⏳",
        'finished_uploading': "Yuklab bo'lindi. Jonatilmoqda... 🚀",
        'video_caption': "🎵 <b>{title}</b>\n\nYuklab olish formatlari ↓",
        'video_only_caption': "🎵 <b>{title}</b>",
        'btn_video': "🎬 Video",
        'btn_audio': "🎧 MP3",
        'btn_save': "💾 Saqlash",
        'btn_download_song': "📥 Qo'shiqni yuklab olish",
        'btn_add_group': "➕ Guruhga qo'shish ⤴️",
        'btn_close': "❌ Yopish",
        'btn_back': "🔙 Orqaga",
        'voice_listening': "🎤 Ovozli xabar eshitilmoqda...",
        'voice_you_said': "🗣 Siz dedingiz: {text}",
        'voice_error': "🤷‍♂️ Uzr, nima deganingizni tushunmadim.",
        'audio_caption': "🔊 {artist} - {title} ➡\n\n📥 @universal_media_uz_bot orqali istagan musiqangizni tez va oson toping!🚀",
        'file_too_large': "⚠️ Fayl hajmi juda katta ({size} MB). Telegram limiti 50 MB.\nIltimos, pastroq sifatni tanlang yoki boshqa havola yuboring.",
        'video_quality_select': "🎬 Video sifatini tanlang:", 
        'results_title': "🔎 Natijalar ({page}/{total}):\n\n",
        'download_error': "Yuklanmadi 😢",
        'search_results_expired': "Qidiruv natijalari eskirgan.",
        'error_item_not_found': "Xatolik: Element topilmadi",
        'error_link_expired': "Xatolik yuz berdi. Iltimos, qaytadan link yuboring.",
        'voice_convert_error': "⚠️ Ovoz formatini o'zgartirishda xatolik.\nFFmpeg o'rnatilganligini tekshiring.",
        'voice_google_error': "⚠️ Google Speech xizmatida xatolik: {error}",
        'menu_tg_anon': "Telegramda yashirincha 👀",
        'menu_insta_anon': "Instagramda yashirincha 👀",
        'feature_soon': "🛠 Bu funksiya tez orada ishga tushadi!",
        'insta_anon_instruction': "Instagram story havolasini yuboring.",
        'tg_anon_instruction': "Kimning telegramdagi hikoyasini yashirincha ko'rmoqchisiz?\nFoydalanuvchi nomi yoki kontaktini yuboring.",
        'btn_video_manual': "Video qo'llanma 🏷",
        'story_menu_today': "👀 Bugungi hikoyalarni ko'rish",
        'story_menu_old': "👀 Eski hikoyalarni ko'rish",
        'btn_8d': "🎧 8D",
        'btn_concert': "🏟 Concert Hall",
        'btn_slowed': "🐢 Slowed",
        'btn_bass': "🔊 Bass",
        'select_effect': "Iltimos, o'zingizga kerakli variantni tanlang 👇",
        'recognition_processing': "🎧 Media tahlil qilinmoqda... (Music Recognition)",
        'music_recognized': "🎵 <b>Musiqa aniqlandi!</b>\n\n",
        'music_artist': "🎤 Ijrochi: <b>{artist}</b>\n",
        'music_title': "🎼 Nomi: <b>{title}</b>\n",
        'music_not_found': "Musiqa aniqlanmadi (No music found).",
        'music_fallback_search': "⚠️ Musiqa aniqlanmadi. Fayl nomi bo'yicha qidirilmoqda: {query}",
        'music_fallback_failed': "Musiqa aniqlanmadi va qidiruv natija bermadi.",
        'btn_more_links': "Ko'proq havolalar 🔗",
        'btn_telegram_search': "📥 Telegram",
        'top_menu_text': "🎵 <b>Top Musiqalar Bo'limi</b>\n\nQaysi turdagi musiqalarni qidirmoqchisiz?",
        'cat_uz': "🇺🇿 O'zbek Xitlari",
        'cat_world': "🌍 Jahon Xitlari",
        'cat_trend': "🔥 Trend (TikTok/Reels)",
        'cat_new': "🆕 Yangi Chiqqanlar",
        'cat_bass': "🔊 Bass / Avto",
        'btn_find_music': "Musiqani aniqlash 🔎"
    },
    'uz_cyrl': {
        'start_welcome': "Ассалому алейкум Universal Media Bot га\nхуш келибсиз\n@universal_media_uz_bot орқали қуйидагиларни юклаб\nолишингиз мумкин\n\n●Instagram - post, stories, reels;\n●YouTube - video, shorts, audio;\n●Tik Tok - сув белгисиз видео;\n●Facebook - reels\n●VK - video;\n●Pinterest-расм, видео\n●Snapchat-расм, видео\n●Likee - расм, видео\n●Threads -расм, видео\n●Bigo Live - видео, эфир\nМедиа юклашни бошлаш учун\nунинг ҳаволасини юборинг.",
        'search_searching': "🔥 '{query}' бўйича топ мусиқалар қидирилмоқда...",
        'search_top_loading': "🔥 Топ ўзбек мусиқалари қидирилмоқда...",
        'search_not_found': "Ҳозирча топ мусиқалар топилмади.",
        'getting_info': "⏳ Маълумот олинмоқда...",
        'search_music_searching': "🔎 Музика қидирилмоқда: {query}...",
        'nothing_found': "Ҳеч нарса топилмади 😔",
        'no_favorites': "❤️ Сизда ҳозирча сақланган мусиқалар йўқ.",
        'favorites_header': "❤️ <b>Севимли Мусиқалар:</b>\n\n",
        'saved': "❤️ Сақланди!",
        'already_saved': "Аллақачон мавжуд!",
        'saved_msg': "✅ Сақланди: {title}",
        'error_no_link': "Сақлаш учун ҳавола топилмади.",
        'error_general': "Хатолик: {error}",
        'choose_quality': "❤️ Танланди: {title}\n\nСифатни танланг:",
        'lang_choose': "💬 Ўзгартирмоқчи бўлган тилни танланг ва сиз танлаган тилда бот ишлашни бошлайди.\n\n(Интерфейс тилини танлаш учун, пастдаги тугмалардан бирини босишингиз мумкин)",
        'lang_selected': "✅ Тил ўзгартирилди: Ўзбекча 🇺🇿",
        'downloading': "Юкланмоқда... 0%",
        'downloading_percent': "Юкланмоқда... {percent} ⏳",
        'finished_uploading': "Юклаб бўлинди. Жўнатилмоқда... 🚀",
        'video_caption': "🎵 <b>{title}</b>\n\nЮклаб олиш форматлари ↓",
        'video_only_caption': "🎵 <b>{title}</b>",
        'btn_video': "🎬 Видео",
        'btn_audio': "🎧 MP3",
        'btn_save': "💾 Сақлаш",
        'btn_download_song': "📥 Қўшиқни юклаб олиш",
        'btn_add_group': "➕ Гуруҳга қўшиш ⤴️",
        'btn_close': "❌ Ёпиш",
        'btn_back': "🔙 Орқага",
        'voice_listening': "🎤 Овозли хабар эшитилмоқда...",
        'voice_you_said': "🗣 Сиз дедингиз: {text}",
        'voice_error': "🤷‍♂️ Узр, нима деганингизни тушунмадим.",
        'file_too_large': "⚠️ Файл хажми жуда катта ({size} MB). Телеграм лимити 50 MB.\nИлтимос, пастроқ сифатни танланг ёки бошқа ҳавола юборинг.",
        'video_quality_select': "🎬 Видео сифатини танланг:",
        'results_title': "🔎 Натижалар ({page}/{total}):\n\n",
        'download_error': "Юкланмади 😢",
        'search_results_expired': "Қидирув натижалари эскирган.",
        'error_item_not_found': "Хатолик: Элемент топилмади",
        'error_link_expired': "Хатолик юз берди. Илтимос, қайтадан линк юборинг.",
        'voice_convert_error': "⚠️ Овоз форматини ўзгартиришда хатолик.\nFFmpeg ўрнатилганлигини текширинг.",
        'voice_google_error': "⚠️ Google Speech хизматида хатолик: {error}",
        'menu_tg_anon': "Телеграмда яширинча 👀",
        'menu_insta_anon': "Инстаграмда яширинча 👀",
        'feature_soon': "🛠 Бу функция тез орада ишга тушади!",
        'insta_anon_instruction': "Instagram story ҳаволасини юборинг.",
        'tg_anon_instruction': "Кимнинг телеграмдаги ҳикоясини яширинча кўрмоқчисиз?\nФойдаланувчи номи ёки контакдини юборинг.",
        'btn_video_manual': "Видео қўлланма 🏷",
        'story_menu_today': "👀 Бугунги ҳикояларни кўриш",
        'story_menu_old': "👀 Эски ҳикояларни кўриш",
        'btn_8d': "🎧 8D",
        'btn_concert': "🏟 Concert Hall",
        'btn_slowed': "🐢 Slowed",
        'btn_bass': "🔊 Bass",
        'select_effect': "Илтимос, ўзингизга керакли вариантни танланг 👇",
        'recognition_processing': "🎧 Медиа таҳлил қилинмоқда... (Music Recognition)",
        'music_recognized': "🎵 <b>Мусиқа аниқланди!</b>\n\n",
        'music_artist': "🎤 Ижрочи: <b>{artist}</b>\n",
        'music_title': "🎼 Номи: <b>{title}</b>\n",
        'music_not_found': "Мусиқа аниқланмади (No music found).",
        'music_fallback_search': "⚠️ Мусиқа аниқланмади. Файл номи бўйича қидирилмоқда: {query}",
        'music_fallback_failed': "Мусиқа аниқланмади ва қидирув натижа бермади.",
        'btn_more_links': "Кўпроқ ҳаволалар 🔗",
        'btn_telegram_search': "📥 Telegram",
        'top_menu_text': "🎵 <b>Топ Мусиқалар Бўлими</b>\n\nҚайси турдаги мусиқаларни қидирмоқчисиз?",
        'cat_uz': "🇺🇿 Ўзбек Хитлари",
        'cat_world': "🌍 Жаҳон Хитлари",
        'cat_trend': "🔥 Тренд (TikTok/Reels)",
        'cat_new': "🆕 Янги Чиққанлар",
        'cat_bass': "🔊 Bass / Авто",
        'btn_find_music': "Мусиқани аниқлаш 🔎"
    },
    'ru': {
        'start_welcome': "Добро пожаловать в Universal Media Bot\n\nЧерез @universal_media_uz_bot вы можете скачать:\n\n●Instagram - посты, сторис, рилс;\n●YouTube - видео, шортс, аудио;\n●Tik Tok - видео без водяных знаков;\n●Facebook - рилс\n●VK - видео;\n●Pinterest - фото, видео\n●Snapchat - фото, видео\n●Likee - фото, видео\n●Threads - фото, видео\n●Bigo Live - видео, эфир\nДля начала отправьте ссылку.",
        'search_searching': "🔥 Поиск топ музыки по '{query}'...",
        'search_top_loading': "🔥 Поиск топ узбекской музыки...",
        'search_not_found': "Топ музыка пока не найдена.",
        'getting_info': "⏳ Получение информации...",
        'search_music_searching': "🔎 Поиск музыки: {query}...",
        'nothing_found': "Ничего не найдено 😔",
        'no_favorites': "❤️ У вас пока нет сохраненной музыки.",
        'favorites_header': "❤️ <b>Избранная музыка:</b>\n\n",
        'saved': "❤️ Сохранено!",
        'already_saved': "Уже существует!",
        'saved_msg': "✅ Сохранено: {title}",
        'error_no_link': "Ссылка для сохранения не найдена.",
        'error_general': "Ошибка: {error}",
        'choose_quality': "❤️ Выбрано: {title}\n\nВыберите качество:",
        'lang_choose': "💬 Выберите язык, который хотите использовать, и бот начнет работать на выбранном вами языке.\n\n(Для выбора языка интерфейса нажмите одну из кнопок ниже)",
        'lang_selected': "✅ Язык изменен: Русский 🇷🇺",
        'downloading': "Загрузка... 0%",
        'downloading_percent': "Загрузка... {percent} ⏳",
        'finished_uploading': "Загружено. Отправка... 🚀",
        'video_caption': "🎵 <b>{title}</b>\n\nФорматы загрузки ↓",
        'video_only_caption': "🎵 <b>{title}</b>",
        'btn_video': "🎬 Видео",
        'btn_audio': "🎧 MP3",
        'btn_save': "💾 Сохранить",
        'btn_download_song': "📥 Скачать песню",
        'btn_add_group': "➕ Добавить в группу ⤴️",
        'btn_close': "❌ Закрыть",
        'btn_back': "🔙 Назад",
        'voice_listening': "🎤 Слушаю голосовое сообщение...",
        'voice_you_said': "🗣 Вы сказали: {text}",
        'voice_error': "🤷‍♂️ Извините, я не понял, что вы сказали.",
        'file_too_large': "⚠️ Размер файла слишком большой ({size} MB). Лимит Telegram 50 MB.\nПожалуйста, выберите качество ниже или отправьте другую ссылку.",
        'video_quality_select': "🎬 Выберите качество видео:",
        'results_title': "🔎 Результаты ({page}/{total}):\n\n",
        'download_error': "Не загружено 😢",
        'search_results_expired': "Результаты поиска устарели.",
        'error_item_not_found': "Ошибка: Элемент не найден",
        'error_link_expired': "Произошла ошибка. Пожалуйста, отправьте ссылку еще раз.",
        'voice_convert_error': "⚠️ Ошибка конвертации аудио.\nПроверьте установку FFmpeg.",
        'voice_google_error': "⚠️ Ошибка Google Speech: {error}",
        'menu_tg_anon': "Анонимно в Telegram 👀",
        'menu_insta_anon': "Анонимно в Instagram 👀",
        'feature_soon': "🛠 Эта функция скоро станет доступна!",
        'insta_anon_instruction': "Отправьте ссылку на Instagram story.",
        'tg_anon_instruction': "Чьи истории в Telegram вы хотите просмотреть тайно?\nОтправьте имя пользователя или контакт.",
        'btn_video_manual': "Видео инструкция 🏷",
        'story_menu_today': "👀 Посмотреть истории за сегодня",
        'story_menu_old': "👀 Посмотреть старые истории",
        'btn_8d': "🎧 8D",
        'btn_concert': "🏟 Concert Hall",
        'btn_slowed': "🐢 Slowed",
        'btn_bass': "🔊 Bass",
        'select_effect': "Пожалуйста, выберите нужный вариант 👇",
        'recognition_processing': "🎧 Анализ медиа... (Music Recognition)",
        'music_recognized': "🎵 <b>Музыка распознана!</b>\n\n",
        'music_artist': "🎤 Исполнитель: <b>{artist}</b>\n",
        'music_title': "🎼 Название: <b>{title}</b>\n",
        'music_not_found': "Музыка не распознана (No music found).",
        'music_fallback_search': "⚠️ Музыка не распознана. Поиск по имени файла: {query}",
        'music_fallback_failed': "Музыка не распознана и поиск не дал результатов.",
        'btn_more_links': "Больше ссылок 🔗",
        'btn_telegram_search': "📥 Telegram",
        'top_menu_text': "🎵 <b>Топ Музыка</b>\n\nКакую музыку вы ищете?",
        'cat_uz': "🇺🇿 Узбекские Хиты",
        'cat_world': "🌍 Мировые Хиты",
        'cat_trend': "🔥 Тренд (TikTok/Reels)",
        'cat_new': "🆕 Новинки",
        'cat_bass': "🔊 Bass / Авто",
        'btn_find_music': "Определить музыку 🔎"
    },
    'en': {
        'start_welcome': "Welcome to Universal Media Bot\n\nYou can download from:\n\n●Instagram - posts, stories, reels;\n●YouTube - videos, shorts, audio;\n●Tik Tok - no watermark;\n●Facebook - reels\n●VK - videos;\n●Pinterest - photos, videos\n●Snapchat - photos, videos\n●Likee - photos, videos\n●Threads - photos, videos\n●Bigo Live - videos, lives\nSend a link to start downloading.",
        'search_searching': "🔥 Searching top music for '{query}'...",
        'search_top_loading': "🔥 Searching top Uzbek music hits...",
        'search_not_found': "No top music found yet.",
        'getting_info': "⏳ Fetching info...",
        'search_music_searching': "🔎 Searching music: {query}...",
        'nothing_found': "Nothing found 😔",
        'no_favorites': "❤️ You don't have any saved music yet.",
        'favorites_header': "❤️ <b>Favorite Music:</b>\n\n",
        'saved': "❤️ Saved!",
        'already_saved': "Already exists!",
        'saved_msg': "✅ Saved: {title}",
        'error_no_link': "No link found to save.",
        'error_general': "Error: {error}",
        'choose_quality': "❤️ Selected: {title}\n\nChoose quality:",
        'lang_choose': "💬 Select the language you want to change, and the bot will start working in the language you selected.\n\n(To select the interface language, you can click one of the buttons below)",
        'lang_selected': "✅ Language changed: English 🇺🇸",
        'downloading': "Downloading... 0%",
        'downloading_percent': "Downloading... {percent} ⏳",
        'finished_uploading': "Downloaded. Sending... 🚀",
        'video_caption': "🎵 <b>{title}</b>\n\nDownload formats ↓",
        'video_only_caption': "🎵 <b>{title}</b>",
        'btn_video': "🎬 Video",
        'btn_audio': "🎧 MP3",
        'btn_save': "💾 Save",
        'btn_download_song': "📥 Download Song",
        'btn_add_group': "➕ Add to Group ⤴️",
        'btn_close': "❌ Close",
        'btn_back': "🔙 Back",
        'voice_listening': "🎤 Listening to voice message...",
        'voice_you_said': "🗣 You said: {text}",
        'voice_error': "🤷‍♂️ Sorry, I didn't understand that.",
        'file_too_large': "⚠️ File is too large ({size} MB). Telegram limit is 50 MB.\nPlease select lower quality or send another link.",
        'video_quality_select': "🎬 Select video quality:",
        'results_title': "🔎 Results ({page}/{total}):\n\n",
        'download_error': "Download failed 😢",
        'search_results_expired': "Search results expired.",
        'error_item_not_found': "Error: Item not found",
        'error_link_expired': "An error occurred. Please send the link again.",
        'voice_convert_error': "⚠️ Audio conversion error.\nCheck FFmpeg installation.",
        'voice_google_error': "⚠️ Google Speech error: {error}",
        'menu_tg_anon': "Secretly on Telegram 👀",
        'menu_insta_anon': "Secretly on Instagram 👀",
        'feature_soon': "🛠 This feature will be available soon!",
        'insta_anon_instruction': "Send the Instagram story link.",
        'tg_anon_instruction': "Whose Telegram stories do you want to view secretly?\nSend the username or contact.",
        'btn_video_manual': "Video tutorial 🏷",
        'story_menu_today': "👀 View today's stories",
        'story_menu_old': "👀 View old stories",
        'btn_8d': "🎧 8D",
        'btn_concert': "🏟 Concert Hall",
        'btn_slowed': "🐢 Slowed",
        'btn_bass': "🔊 Bass",
        'select_effect': "Please select the option you want 👇",
        'recognition_processing': "🎧 Analyzing media... (Music Recognition)",
        'music_recognized': "🎵 <b>Music Recognized!</b>\n\n",
        'music_artist': "🎤 Artist: <b>{artist}</b>\n",
        'music_title': "🎼 Title: <b>{title}</b>\n",
        'music_not_found': "Music recognition failed (No music found).",
        'music_fallback_search': "⚠️ Music not recognized. Searching by filename: {query}",
        'music_fallback_failed': "Music not recognized and search yielded no results.",
        'btn_more_links': "More Links 🔗",
        'btn_telegram_search': "📥 Telegram",
        'top_menu_text': "🎵 <b>Top Music Menu</b>\n\nWhat kind of music are you looking for?",
        'cat_uz': "🇺🇿 Uzbek Hits",
        'cat_world': "🌍 World Hits",
        'cat_trend': "🔥 Trending (TikTok)",
        'cat_new': "🆕 New Releases",
        'cat_bass': "🔊 Bass / Car",
        'btn_find_music': "Find Music 🔎"
    }
}
